apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
    app.kubernetes.io/component: client
    app.kubernetes.io/instance: client
    app.kubernetes.io/name: golang
    app.kubernetes.io/part-of: hello-world-server
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.13.4-ubi7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
        deploymentconfig: client
    spec:
      containers:
      - env:
        - name: HOST
          value: http://server:8080
        image: image-registry.openshift-image-registry.svc:5000/hello-world-go/client@sha256:f1f254278ae557804406b69c9dcc90dc77e9aa5584a9b9a554b03e4ec2d5a2ce
        imagePullPolicy: Always
        name: client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-25T11:43:18Z"
    lastUpdateTime: "2021-01-25T11:43:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-25T11:41:39Z"
    lastUpdateTime: "2021-01-25T11:43:18Z"
    message: ReplicaSet "client-6d97b849f6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
